const para = [
    "Ancient manuscripts also divided sentences into paragraphs with line breaks (newline) followed by an initial at the beginning of the next paragraph. An initial is an oversized capital letter, sometimes outdented beyond the margin of the text. This style can be seen, for example, in the original Old English manuscript of Beowulf. Outdenting is still used in English typography, though not commonly.[2] Modern English typography usually indicates a new paragraph by indenting the first line. This style can be seen in the (handwritten) United States Constitution from 1787. For additional ornamentation, a hedera leaf or other symbol can be added to the inter-paragraph white space, or put in the indentation space.",

    "In word processing and desktop publishing, a hard return or paragraph break indicates a new paragraph, to be distinguished from the soft return at the end of a line internal to a paragraph. This distinction allows word wrap to automatically re-flow text as it is edited, without losing paragraph breaks. he crafting of clear, coherent paragraphs is the subject of considerable stylistic debate. ",

    "The software may apply vertical white space or indenting at paragraph breaks, depending on the selected style. How such documents are actually stored depends on the file format. For example, HTML uses the <p> tag as a paragraph container. In plaintext files, there are two common formats. The pre-formatted text will have a newline at the end of every physical line, and two newlines at the end of a paragraph, creating a blank line. An alternative is to only put newlines at the end of each paragraph, and leave word wrapping up to the application that displays or processes the text.",

    "The crafting of clear, coherent paragraphs is the subject of considerable stylistic debate. The form varies among different types of writing. For example, newspapers, scientific journals, and fictional essays have somewhat different conventions for the placement of paragraph breaks.A common English usage misconception is that a paragraph has three to five sentences; single-word paragraphs can be seen in some professional writing, and journalists often use single-sentence paragraphs.[7].",

    "English students are sometimes taught that a paragraph should have a topic sentence or 'main idea', preferably first, and multiple 'supporting' or 'detail' sentences that explain or supply evidence. One technique of this type, intended for essay writing, is known as the Schaffer paragraph. Topic sentences are largely a phenomenon of school-based writing, and the convention does not necessarily obtain in other contexts.[8] This advice is also culturally specific, for example, it differs from stock advice for the construction of paragraphs in Japanese",

    "We live in this house Where there are polished slabs of wooden flooring, carpet, the color of dust-strewn olive, once  lay. Our kitchen walls were a brigarish yellow meant to help us mark the sunrises. Every room felt bigger and more mysterious then than they do now, for you and I grown tall tall enough to see, tall enough to reach. Where dirt and dust from the years coated our lives, now little drafts dthrough. We live in this house on the corner of South Central. We always have, we always will. ",

    "Even as the world sickens and crumbles around us, here, time will stand still. I cannot balance moments with margins of eternity that remember me with grace. Maybe it was early in 2019 when I watched a pink music video where beautiful young men danced and sang about love and love and love. I'm not sure anymore because I cannot  moments with margins of eternity that remember us with grace and poise, but also with a gentle note of scolding. A year later, I had universes of information about them whizzing through my head so surely that the only obvious way to release assign essays to my students about their galaxy ",

    "The indefinite article takes two forms. It's the word a when it precedes a word that begins with a consonant. It's the word an when it precedes a word that begins with a vowel. The indefinite article indicates that a noun refers to a general idea rather than a particular thing. For example, you might ask your friend, “Should I bring a gift to the party?” Your friend will understand that you are not asking about a specific type of gift or a specific item. “I am going to bring an apple pie,” your friend tells you. Again, the indefinite article indicates that she is not talking about a specific apple pie. Your friend probably doesn't even have any pie yet. The indefinite article only appears with singular nouns. Consider the following examples of indefinite articles used in context:",

    "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Iure blanditiis numquam expedita amet nobis aut ea nesciunt iusto culpa nulla voluptatibus in ex nostrum, reprehenderit voluptas? Minima, doloribus? Unde doloribus fugit molestiae non illum eius corrupti officia nesciunt! Magnam perspiciatis quae tenetur vero. Molestiae reiciendis quae magni eius quisquam recusandae possimus veniam quia culpa est totam voluptatibus architecto sunt et ullam, voluptates expedita? Molestias laudantium architecto vel!",
    
    " Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam voluptates alias eius corporis recusandae, veritatis soluta optio asperiores atque, aliquam reprehenderit dignissimos impedit quo beatae quaerat earum, perspiciatis at corrupti? Excepturi reiciendis quis ea, repellendus cum ipsam. Expedita vel eos consequuntur. Enim aspernatur, natus quis necessitatibus velit inventore quam, voluptatibus, reiciendis officiis praesentium dignissimos dolore sint tenetur labore voluptatum possimus incidunt. Dolor fugiat sed ea magnam reiciendis beatae fugit. Repellat nulla incidunt alias dolore. Eum temporibus aut maiores!",

    "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsa reiciendis nam ipsam, facere, autem est aliquid at repellat molestias aspernatur cumque porro fugit. Corrupti excepturi maxime est iste vitae voluptatibus itaque totam nulla autem dolorum, vel at, praesentium nihil debitis? Incidunt tempora magnam itaque odit autem quibusdam in? Exercitationem ipsam voluptate unde quisquam ut maxime, porro temporibus distinctio accusamus numquam, cumque similique aliquid! Iusto quo dign, a qui molestiae quis laboriosam vero? Maiores aliquam id iusto cumque laborum, dolor placeat quo incidunt vel quae earum quasi rem voluptatem pariatur officia nam quibusdam, nemo, ad excepturi itaque? Voluptatibus maiores quibusdam tempore corporis saepe unde temporibus molestias aliquam culpa excepturi error, nesciunt nostrum dolor."
];